# Generated by Django 4.1.1 on 2022-09-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_homework_description_homework_homework_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='homework_name',
            new_name='connection_with_task',
        ),
        migrations.AddField(
            model_name='homework',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to=settings.AUTH_USER_MODEL),
        ),
    ]
