# Generated by Django 4.1.1 on 2022-09-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_homework_connection_with_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_status',
            field=models.CharField(choices=[('Pending verification', 'Pending Verification'), ('Completed', 'Completed'), ('Wrong', 'Not Satisfied')], default='Pending verification', max_length=255),
        ),
    ]
