# Generated by Django 4.1.1 on 2022-09-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_homework_homework_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework_status',
        ),
        migrations.CreateModel(
            name='HomeworkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.CharField(choices=[('Pending verification', 'Pending Verification'), ('Completed', 'Completed'), ('Wrong', 'Not Satisfied')], default='Pending verification', max_length=255)),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_status', to='tasks.homework')),
            ],
        ),
    ]
