# Generated by Django 4.1.1 on 2022-09-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_homework_homework_status_homeworkstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkstat',
            name='status',
        ),
        migrations.AddField(
            model_name='homeworkstat',
            name='homework',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='tasks.homework'),
        ),
        migrations.AlterField(
            model_name='homeworkstat',
            name='status_value',
            field=models.CharField(choices=[('Pending verification', 'Pending Verification'), ('Completed', 'Completed'), ('Wrong', 'Wrong')], default='Pending verification', max_length=255),
        ),
    ]
