# Generated by Django 4.1.1 on 2022-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_homeworkstat_homework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_status',
            field=models.CharField(choices=[('Pending verification', 'Pending Verification'), ('Completed', 'Completed'), ('Wrong', 'Wrong')], default='Pending verification', max_length=255),
        ),
        migrations.DeleteModel(
            name='HomeworkStat',
        ),
    ]
