# Generated by Django 4.1.1 on 2022-09-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_alter_group_group_status'),
        ('tasks', '0010_taskcomment_homeworkcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='responsible_group',
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='groups.group'),
        ),
    ]
