# Generated by Django 4.1.1 on 2022-09-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_comment_taskcomment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkcomment',
            name='homework',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='HomeworkComment',
        ),
    ]
