# Generated by Django 4.1.1 on 2022-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_status', models.CharField(choices=[('Active', 'Active'), ('Diploma', 'Diploma'), ('Break', 'Break'), ('Issued', 'Issued'), ('Preparing', 'Preparing')], default='Preparing', max_length=255)),
            ],
        ),
    ]
