# Generated by Django 4.1.1 on 2022-09-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Diploma', 'Diploma'), ('Break', 'Break'), ('Issued', 'Issued'), ('Preparing', 'Preparing')], default='Preparing', max_length=255),
        ),
    ]
