# Generated by Django 4.1.1 on 2022-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='merch.images')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In processing', 'In Processing'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='In processing', max_length=255)),
                ('purchased_item', models.ManyToManyField(related_name='purchased', to='merch.merchshop')),
            ],
        ),
    ]
