# Generated by Django 4.1.1 on 2022-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_merch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
