# Generated by Django 4.1.1 on 2022-09-22 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merch', '0003_alter_merch_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In processing', 'In Processing'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='In processing', max_length=255)),
                ('purchased_item', models.ManyToManyField(related_name='purchased', to='merch.merch')),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
