# Generated by Django 4.1.1 on 2022-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
