# Generated by Django 4.1.1 on 2022-09-10 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0011_alter_group_group_status'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_status',
            field=models.CharField(choices=[('Pending verification', 'Pending Verification'), ('Completed', 'Completed'), ('Not satisfied', 'Not Satisfied')], default='Pending verification', max_length=255),
        ),
        migrations.AddField(
            model_name='homework',
            name='links',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_group',
            field=models.ManyToManyField(blank=True, related_name='task', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
