# Generated by Django 4.1.1 on 2022-09-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_homework_name_homework_connection_with_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='connection_with_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='tasks.task'),
        ),
    ]
