# Generated by Django 4.1.1 on 2022-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_responsible_group_task_responsible_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.taskcomment'),
        ),
    ]
