# Generated by Django 4.1.1 on 2022-09-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_homeworkcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
