# Generated by Django 4.1.1 on 2022-09-08 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_status', models.CharField(choices=[('Active', 'Active'), ('Diploma', 'Diploma'), ('Break', 'Break'), ('Issued', 'Issued')], default='Preparing', max_length=255)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
