# Generated by Django 4.1.1 on 2022-09-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255)),
                ('lesson_status', models.CharField(choices=[('Conducted', 'Conducted'), ('Not conducted', 'Not Conducted')], default='Not conducted', max_length=255)),
                ('description', models.TextField()),
                ('record_download_link', models.URLField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('connection_with_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='groups.group')),
            ],
        ),
    ]
